### ISSUE TITLE
Slight modification to printing the after contest rankings

### ISSUE THREAD

**Issue by vidit-jain** [Groverkss/TLE#20]
I believe we should modify the after contest such that if there were no unofficial participants in the contest, we just print one rank list and embed object, instead of the current way of creating a block that says the official rankings are the same as the all rankings.

Maybe we could modify the embed object such that when there are no unofficial participants, we print only one embed object with the title "Top five ranks (Official & All)".

**Comment by GaurangTandon** [comment]
Verified commit works, message link: https://discord.com/channels/710822875443101706/712406461439017020/861286472660811836
