### ISSUE TITLE
Auto-correct ;dual to ;duel

### ISSUE THREAD

**Issue by GaurangTandon** [Groverkss/TLE#7]
Please :pray:

**Comment by Groverkss** [comment]
Problem with this is that 'duel' is actually the cog name. If discord does not provide this feature i'm not sure how we will implement this. Any ideas how we can?

**Comment by GaurangTandon** [comment]
I was looking into the possibility of allowing multiple aliased names for a given cog. These additional alias names should not show up in the `;help` text, or if they do, they should be clearly marked as spelling variations.

For example, from [duel.py](https://github.com/Groverkss/TLE/blob/294badc870e301406ef4d484b956d720dcbee00a/tle/cogs/duel.py), 

    @commands.group(brief="Duel commands", invoke_without_command=True)
    async def dual(self, ctx):
        """Alias for duel"""
        await ctx.send_help(ctx.command)

    @commands.group(brief="Duel commands", invoke_without_command=True)
    async def duel(self, ctx):
        """Group for commands pertaining to duels"""
        await ctx.send_help(ctx.command)

    @dual.command(brief="Register a duelist")
    @duel.command(brief="Register a duelist")
    async def register(self, ctx, member: discord.Member):
        """Register a duelist"""

But I don't know if it'll actually work that way (?)

**Comment by Groverkss** [comment]
Check this also:

 https://stackoverflow.com/questions/50204867/how-to-give-a-command-multiple-names

**Comment by GaurangTandon** [comment]
`@client.command(pass_context = True , aliases=['purge', 'clean', 'delete'])`

From the post you linked, sounds like we should this should work for our case also.

**Comment by Groverkss** [comment]
@Vidit-Jain Add this and rerun the both thx

https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#discord.ext.commands.Command.aliases
